---
  {{- if .Values.onosApiPort }}
apiVersion: v1
kind: Service
metadata:
  name: onos-api
spec:
  type: NodePort
  ports:
    - name: onos-api
      port: 8181
      nodePort: {{ .Values.onosApiPort }}
  selector:
    app: {{ template "fullname" . }}
  {{- end}}
---
  {{- if .Values.onosSshPort }}
apiVersion: v1
kind: Service
metadata:
  name: onos-ssh
spec:
  type: NodePort
  ports:
    - name: onos-ssh
      port: 8101
      nodePort: {{ .Values.onosSshPort }}
  selector:
    app: {{ template "fullname" . }}
  {{- end}}

# workaround for . not working, see
# https://github.com/helm/helm/issues/1311
{{- $root := . -}}
{{ range $k, $index := until (atoi (quote .Values.replicas) | default 3) }}
---
apiVersion: v1
kind: Service
metadata:
  name: onos-of-{{ $index }}
spec:
  type: NodePort
  ports:
    - name: onos-of-{{ $index }}
      #starting from 6654 not to break backwards compatibility with existing -hs service and node ports
      port: {{ add $index 6654 }}
      nodePort: {{ add $index 31654 }}
  selector:
    app: {{ template "fullname" $root }}
{{ end }}