---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-hs
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  {{- with .Values.ports }}
  ports:
  {{- range . }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: {{ .protocol | default "TCP" | quote }}
  {{- end }}
  {{- end }}
  # ONOS and Atomix need to be able to talk to each other for ONOS to become ready
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: {{ template "fullname" . }}

# workaround for . not working, see
# https://github.com/helm/helm/issues/1311
{{- $root := . -}}
{{ range $k, $index := until (atoi (quote .Values.replicas) | default 3) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" $root }}-{{ $index }}
  labels:
    app: {{ template "fullname" $root }}
    chart: "{{ $root.Chart.Name }}-{{ $root.Chart.Version }}"
    release: "{{ $root.Release.Name }}"
    heritage: "{{ $root.Release.Service }}"
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: openflow
    #starting from 6654 not to break backwards compatibility with existing -hs service and node ports
    port: {{ add $index 6654 }}
    targetPort: 6653
    protocol: TCP
  {{- with $root.Values.ports }}
  {{- range . }}
  - name: {{ .name }}
    port: {{ .port }}
    protocol: {{ .protocol | default "TCP" | quote }}
  {{- end }}
  {{- end }}
  # ONOS and Atomix need to be able to talk to each other for ONOS to become ready
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: {{ template "fullname" $root }}
{{ end }}

